{
  "Graph": {
    "__version": 6,
    "__guid": "1b02e767-e033-44fd-bd94-66feb64bef85",
    "UserData": {
      "Title": "Ammo Trigger",
      "Description": "No description provided.",
      "Icon": "account_tree",
      "Category": "Custom",
      "ReferencedComponentTypes": []
    },
    "Parameters": {
      "Inputs": [
        {
          "Name": "_in1",
          "Type": "Sandbox.Game/Sandbox.Collider",
          "Display": {
            "Title": "Input 1",
            "Hidden": false
          },
          "UsedBy": [
            "_signal"
          ]
        }
      ],
      "DefaultSignals": true
    },
    "Variables": [],
    "Nodes": [
      {
        "Id": 0,
        "Type": "input",
        "UserData": {
          "Position": "-1456,-16"
        }
      },
      {
        "Id": 1,
        "Type": "call",
        "Properties": {
          "T": "package.nolankicks.open_world_game/Kicks.AmmoContainer",
          "_name": "TryGet",
          "_type": "Sandbox.Game/Sandbox.IComponentLister",
          "_isStatic": false
        },
        "UserData": {
          "Position": "-1168,-80"
        }
      },
      {
        "Id": 2,
        "Type": "if",
        "UserData": {
          "Position": "-688,-160"
        }
      },
      {
        "Id": 3,
        "Type": "call",
        "Properties": {
          "T": "package.nolankicks.open_world_game/Inventory",
          "_name": "TryGet",
          "_type": "Sandbox.Game/Sandbox.IComponentLister",
          "_isStatic": false
        },
        "UserData": {
          "Position": "-1104,128"
        }
      },
      {
        "Id": 4,
        "Type": "op.and",
        "UserData": {
          "Position": "-848,-16"
        }
      },
      {
        "Id": 5,
        "Type": "call",
        "Properties": {
          "_isStatic": false,
          "_type": "package.nolankicks.open_world_game/Inventory",
          "_name": "AddAmmo"
        },
        "UserData": {
          "Position": "-464,16"
        }
      },
      {
        "Id": 37,
        "Type": "property",
        "Properties": {
          "_type": "Sandbox.Game/Sandbox.GameObject",
          "_name": "Parent"
        },
        "UserData": {
          "Position": "-416,368"
        }
      },
      {
        "Id": 38,
        "Type": "call",
        "Properties": {
          "_isStatic": false,
          "_type": "Sandbox.Game/Sandbox.GameObject",
          "_name": "Destroy"
        },
        "UserData": {
          "Position": "-176,192"
        }
      }
    ],
    "Links": [
      {
        "SrcId": 0,
        "SrcName": "_in1",
        "DstId": 1,
        "DstName": "_target"
      },
      {
        "Value": "EnabledInSelf, InParent",
        "DstId": 1,
        "DstName": "search"
      },
      {
        "SrcId": 0,
        "SrcName": "_signal",
        "DstId": 2,
        "DstName": "_signal"
      },
      {
        "SrcId": 4,
        "SrcName": "_result",
        "DstId": 2,
        "DstName": "condition"
      },
      {
        "SrcId": 0,
        "SrcName": "_in1",
        "DstId": 3,
        "DstName": "_target"
      },
      {
        "Value": "EnabledInSelf, InParent",
        "DstId": 3,
        "DstName": "search"
      },
      {
        "SrcId": 1,
        "SrcName": "_result",
        "DstId": 4,
        "DstName": "a"
      },
      {
        "SrcId": 3,
        "SrcName": "_result",
        "DstId": 4,
        "DstName": "b"
      },
      {
        "SrcId": 2,
        "SrcName": "true",
        "DstId": 5,
        "DstName": "_signal"
      },
      {
        "SrcId": 3,
        "SrcName": "component",
        "DstId": 5,
        "DstName": "_target"
      },
      {
        "Value": 30,
        "DstId": 5,
        "DstName": "ammo"
      },
      {
        "SrcId": 1,
        "SrcName": "component",
        "DstId": 5,
        "DstName": "ammoContainer"
      },
      {
        "Value": "LightAmmo",
        "DstId": 5,
        "DstName": "ammoType"
      },
      {
        "SrcId": 0,
        "SrcName": "_target",
        "DstId": 37,
        "DstName": "_target"
      },
      {
        "SrcId": 5,
        "SrcName": "_signal",
        "DstId": 38,
        "DstName": "_signal"
      },
      {
        "SrcId": 37,
        "SrcName": "_result",
        "DstId": 38,
        "DstName": "_target"
      }
    ]
  },
  "ResourceVersion": 0,
  "__version": 0,
  "__references": []
}