{
  "Graph": {
    "__version": 6,
    "__guid": "e7828b68-13cf-48d4-b6c6-d84eaa740657",
    "UserData": {
      "Title": "Drop Light Ammo Action",
      "ReferencedComponentTypes": []
    },
    "Parameters": {
      "DefaultSignals": true
    },
    "Variables": [],
    "Nodes": [
      {
        "Id": 0,
        "Type": "input"
      },
      {
        "Id": 1,
        "Type": "scene.clone",
        "UserData": {
          "Position": "560,0"
        }
      },
      {
        "Id": 2,
        "Type": "property",
        "Properties": {
          "_type": "Sandbox.Game/Sandbox.GameObject",
          "_name": "Transform"
        },
        "UserData": {
          "Position": "-80,224"
        }
      },
      {
        "Id": 3,
        "Type": "property",
        "Properties": {
          "_type": "Sandbox.Game/Sandbox.GameTransform",
          "_name": "Position"
        },
        "UserData": {
          "Position": "112,192"
        }
      },
      {
        "Id": 4,
        "Type": "op.add",
        "UserData": {
          "Position": "368,192"
        }
      },
      {
        "Id": 5,
        "Type": "vec3.new",
        "UserData": {
          "Position": "80,320"
        }
      }
    ],
    "Links": [
      {
        "SrcId": 0,
        "SrcName": "_signal",
        "DstId": 1,
        "DstName": "_signal"
      },
      {
        "SrcId": 4,
        "SrcName": "_result",
        "DstId": 1,
        "DstName": "position"
      },
      {
        "Value": {
          "_type": "gameobject",
          "prefab": "prefabs/light_ammo_pickup.prefab"
        },
        "DstId": 1,
        "DstName": "target"
      },
      {
        "SrcId": 0,
        "SrcName": "target",
        "DstId": 2,
        "DstName": "_target"
      },
      {
        "SrcId": 2,
        "SrcName": "_result",
        "DstId": 3,
        "DstName": "_target"
      },
      {
        "SrcId": 3,
        "SrcName": "_result",
        "DstId": 4,
        "DstName": "a"
      },
      {
        "SrcId": 5,
        "SrcName": "_result",
        "DstId": 4,
        "DstName": "b"
      },
      {
        "Value": 0,
        "DstId": 5,
        "DstName": "x"
      },
      {
        "Value": 0,
        "DstId": 5,
        "DstName": "y"
      },
      {
        "Value": 55,
        "DstId": 5,
        "DstName": "z"
      }
    ]
  },
  "ResourceVersion": 0,
  "__version": 0,
  "__references": []
}